name: Auto Collect and Push CSV

on:
  schedule:
    - cron: "0 14 * * *"   # UTC 14시 = 한국시간 23시 (매일 밤 11시 실행)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Collector
        run: python collector.py
